### ISSUE TITLE
Allow for Extendable RequestMappingInfo class?

### ISSUE THREAD

**Issue by KostiaPerehuda** [kshashov/spring-boot-starter-telegram#15]
Current API features configurable `RequestMappingsMatcherStrategy` which allows to define a cutom matching behaviour of `TelegramEvent`s to available `HandlerMethod`s. It also features `postProcess` method to alter `RequestMappingInfo` of a  `RequestMapping` should the user need to.
In theory it allows for adding custom data to the `RequestMappingInfo` (by extending the class) and later using this data in `isMatched` method.
Unfortunatelly, `RequestMappingInfo` class is declared to be final and cannot be extended. So far I haven't seen any reasons in the code for this class to final, but I might be wrong. Is it possible to make this class extensible? Thank you.

P.s. An example of why this would be useful, would be a state management system which I want to add over the current API functionality for my personal use. There will be a state manager which will keep record of current state of each User of the Bot, each Controller will be annotated with `State` annotation. And I want the controller methods to be matched to the TelegramEvent only when the User is in the state which is specified in the controller annotation.
Current funcationality allows me to get Annotations of Class of the Controller Methods in `RequestMappingsMatcherStrategy.postProcess` method, however I cannot add this information to `RequestMappingInfo` because it is not extendable.

**Comment by kshashov** [comment]
Good point, this should have been done originally.

Released in 0.27. Should be available soon.

**Comment by KostiaPerehuda** [comment]
Thank you very much, appreciate it:)
