### ISSUE TITLE
How to handle if user sent photo/photos to bot?

### ISSUE THREAD

**Issue by MachinaIlucha** [kshashov/spring-boot-starter-telegram#16]

**Comment by kshashov** [comment]
There are no special shortcuts for stickers in the starter so you will have to load the image according to `com.pengrad.telegrambot.model.Message#sticker` info.

Something like this:
```java
    @BotRequest(value = "", type = {MessageType.MESSAGE})
    public BaseRequest echoImage(Chat chat, Message message, TelegramBot bot) throws IOException {
        GetFileResponse getFile = bot.execute(new GetFile(message.sticker().fileId()));
        String url = bot.getFullFilePath(getFile.file());
        byte[] image = new URL(url).openStream().readAllBytes();
        return new SendSticker(chat.id(), image);
    }
```
I am using https://github.com/pengrad/java-telegram-bot-api inside, you can check their wiki for details.

**Comment by MachinaIlucha** [comment]
> There are no special shortcuts for stickers in the starter so you will have to load the image according to `com.pengrad.telegrambot.model.Message#sticker` info.
> 
> Something like this:
> 
> ```java
>     @BotRequest(value = "", type = {MessageType.MESSAGE})
>     public BaseRequest echoImage(Chat chat, Message message, TelegramBot bot) throws IOException {
>         GetFileResponse getFile = bot.execute(new GetFile(message.sticker().fileId()));
>         String url = bot.getFullFilePath(getFile.file());
>         byte[] image = new URL(url).openStream().readAllBytes();
>         return new SendSticker(chat.id(), image);
>     }
> ```
> 
> I am using https://github.com/pengrad/java-telegram-bot-api inside, you can check their wiki for details.

thank you very much, will try it
