### ISSUE TITLE
How to use GetChatMember?

### ISSUE THREAD

**Issue by ocd0711** [kshashov/spring-boot-starter-telegram#25]
Hi,
Im using this library to create my telegram bot,
i need to use GetChatMemeber to check my user is member of a group, i have read this class code and found no way to how to use it.
could please some write a simple exmaple of how to use this class?

thanks

**Comment by kshashov** [comment]
Hi,

The question relates more to https://github.com/pengrad/java-telegram-bot-api/ than to this starter. To use the `GetChatMember ` and any other request, you should execute it using a `TelegramBot` instance.
```java
    @MessageRequest("/me")
    public String me(Chat chat, User user, TelegramBot bot) {
        GetChatMemberResponse response = bot.execute(new GetChatMember(chat.id(), user.id()));
        return response.chatMember().toString();
    }
```
![Без названия (8)](https://user-images.githubusercontent.com/3830719/211197100-fe046236-cc46-4f40-8cda-10688de63a57.png)
