### ISSUE TITLE
send an asynchronous message

### ISSUE THREAD

**Issue by rccardero** [kshashov/spring-boot-starter-telegram#31]
Is there a method to send a message to the bot to tell the user to wait since the controller hasn't finished executing?

**Comment by kshashov** [comment]
You can get the `com.pengrad.telegrambot.TelegramBot` instance from parameters and send whatever you want.

To be honest, I don't understand the problem. Maybe there is some kind of example?

**Comment by califortovo** [comment]
After analizing issues made some instruction

1. Create config file and assign TelegramBot instance as a static variable
```
@Component
public class BotConfig implements TelegramBotGlobalPropertiesConfiguration {
    @Getter
    @Value("${bot.token}")
    private String token;

    public static TelegramBot telegramBot;

    @Override
    public void configure(TelegramBotGlobalProperties.Builder builder) {

        builder.processBot(token, bot -> {
            telegramBot = bot;
            bot.execute(new SendMessage(396325842, "test"));
        });
    }
}
```

2. In bot application get bot instance and use it
```
TelegramBot bot = BotConfig.telegramBot;
bot.execute(new SendMessage(chatId, "message"));
```

**Comment by kshashov** [comment]
Added this workaround to the readme
