### ISSUE TITLE
Update to Telegram API 6.7

### ISSUE THREAD

**Issue by gumumans** [kshashov/spring-boot-starter-telegram#33]
Hi. I really liked the idea with controllers, what I was looking for. Will there be an update to Telegram Api version 6.7 and Spring version 3.1. Is your version 3.1 Spring Boot up to date?

**Comment by kshashov** [comment]
Are you having problems using the plugin with Spring 3+? It should work fine with the starter version 0.29

By the way, you can exclude the telegram api dependency from my starter and add a more recent version to your project without waiting for a new starter release
