### ISSUE TITLE
Containerizing and Deploying Spring Boot Telegram Bot with Webhook on Heroku

### ISSUE THREAD

**Issue by minhjavapc** [kshashov/spring-boot-starter-telegram#35]
I must say it's fantastic! But I'm interested in containerizing it for more flexibility and better control. Could you please guide me on how to containerize the application and deploy it on Heroku using a container?

Thanks a lots.

**Comment by kshashov** [comment]
You may need to configure the webhook usage. The Docker and Heroku configurations will not be different from those that would be used for any other Spring Boot application.

**Comment by minhjavapc** [comment]
Thank you for your advice! I have successfully configured the webhook with Docker.
