### ISSUE TITLE
Streaming voice message

### ISSUE THREAD

**Issue by minhjavapc** [kshashov/spring-boot-starter-telegram#36]
Hi! Thanks for your contribution. If there is any feature or technique I missed regarding the ability to stream voice directly from users to Spring Boot. If not, do you have any ideas on how to achieve this? I will try to research it myself. Thank you!

**Comment by kshashov** [comment]
Hello!
This library uses https://github.com/pengrad/java-telegram-bot-api/ to interact with Telegram API
It’s better to find out exactly what functionality from that library you need so that I could suggest how you can use it from the controller

**Comment by minhjavapc** [comment]
Thanks a lots!
