### ISSUE TITLE
Cannot use a webhook in Spring Boot 3

### ISSUE THREAD

**Issue by minhjavapc** [kshashov/spring-boot-starter-telegram#37]
Hi! It's me again. But there is a problem when using the webhook in Spring Boot 3. I am currently using Spring Boot 3.0.3 and Java 17. The result cannot create the JavalinServer bean. The detailed error is:

Error creating bean with name 'javalinServer' defined in class path resource [com/github/kshashov/telegram/TelegramAutoConfiguration.class]: Failed to instantiate [io.javalin.Javalin]: Factory method 'javalinServer' threw exception with message: javax/servlet/http/HttpServlet (ClassNotFoundException)

**Comment by kshashov** [comment]
Hi @minhjavapc,
I hope it is fixed in `0.30` plugin version

**Comment by minhjavapc** [comment]
Thank you!
