### ISSUE TITLE
Broken http-handling process

### ISSUE THREAD

**Issue by belochka98** [kshashov/spring-boot-starter-telegram#41]
Hi, kshashov! I noticed several moments, thats needed to be explained:

1. When i use '@BotRequest' and send request to telegram like 'return  new SetMyCommands(commands)' i get some 404-error response, but in logs its seems like `request was successfully executed`, even i get 'BaseResponse{ok=false, error_code=400, description='Bad Request: BOT_COMMAND_INVALID', parameters=null}'
![image](https://github.com/kshashov/spring-boot-starter-telegram/assets/44918892/75fd9f61-d009-43de-bcd5-b494ad6b43cf) 
(e.t.c: that's not the question about "why i get exception", rather then "why its not handled by 'onFailure'")

**Comment by kshashov** [comment]
Hello!
It's probably more efficient to ask in https://github.com/pengrad/java-telegram-bot-api/ repo. I just invoke their `com.pengrad.telegrambot.TelegramBot#execute(T, com.pengrad.telegrambot.Callback<T,R>)`

**Comment by belochka98** [comment]
> Hello! It's probably more efficient to ask in https://github.com/pengrad/java-telegram-bot-api/ repo. I just invoke their `com.pengrad.telegrambot.TelegramBot#execute(T, com.pengrad.telegrambot.Callback<T,R>)`

hmmm... but its 'com.github.kshashov.telegram.handler.DefaultTelegramUpdatesHandler', method 'postExecute', so I thought it was the wrapper, thx
