### ISSUE TITLE
Easy way to delete message

### ISSUE THREAD

**Issue by NatanielBR** [kshashov/spring-boot-starter-telegram#7]
In the same way that using String return, there could be something simpler to delete messages already sent.

Example:

```java
public interface TelegramMvcController{
           String getToken();
           //Its a new code
          default void deleteLastMessage(){
                     //Method using TelegramSession to get a last MessageID and chatID to try a delete a message.
          }
}
```

For each message sends, the Message IF its updated in Telegram Session.
Sorry for any error in my english or if suggestion its idiot.

**Comment by kshashov** [comment]
Thanks for your interest in my library!

I don’t think it’s the responsibility of the library to implement such methods, it should be at the bot level.

Which messages would you like to delete? Those sent by your bot or those received by it? By the way, there are many pitfalls here. For example, the session lifetime is limited, and at some point there will be no necessary information.

**Comment by NatanielBR** [comment]
Ok, if the objective this library it's not implement methods for bot level.

Really, the session it's not good for that purpose.
